# Generated by Django 6.0.3 on 2026-03-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduka', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
