# Generated by Django 6.0.3 on 2026-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduka', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='promotions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='restocks',
            field=models.BooleanField(default=False),
        ),
    ]
